// Code generated by "stringer -type=NodeType"; DO NOT EDIT.

package gtl

import "strconv"

const _NodeType_name = "ProgramTrueFalseIFZeroSuccPredIsZeroVariableFreeVariableLambdaLambdaDefLambdaParamLambdaBodyApply"

var _NodeType_index = [...]uint8{0, 7, 11, 16, 18, 22, 26, 30, 36, 44, 56, 62, 71, 82, 92, 97}

func (i NodeType) String() string {
	if i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
