// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package gtl

import "strconv"

const _TokenType_name = "EOFWordLParenRParenLBlaceRBlaceArrowDotNumberKeyword"

var _TokenType_index = [...]uint8{0, 3, 7, 13, 19, 25, 31, 36, 39, 45, 52}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
